version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3003
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
    container_name: frontend
  backend:
    image: backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./backend/:/usr/src/app
    container_name: backend
  debug-helper:
    image: busybox